import * as pulumi from "@pulumi/pulumi";
import * as postgresql from "@pulumi/postgresql";

const config = new pulumi.Config("postgres");

// Passwords are pre-generated by setup-passwords.ts and stored as Pulumi secrets.
// Run `npm run setup-passwords` (or the GH Actions workflow) before `pulumi up`.
const adminPassword = config.requireSecret("adminPassword");
const appPassword = config.requireSecret("appPassword");

// PostgreSQL role for the application
const crawlerRole = new postgresql.Role("crawler-app", {
  name: "crawler",
  password: appPassword,
  login: true,
});

// Application database
const crawlerDb = new postgresql.Database("crawler-db", {
  name: "crawler",
  owner: crawlerRole.name,
  encoding: "UTF8",
  lcCollate: "en_US.UTF-8",
  lcCtype: "en_US.UTF-8",
});

// Grant all privileges on the database to the app role
new postgresql.Grant("crawler-db-grant", {
  database: crawlerDb.name,
  role: crawlerRole.name,
  objectType: "database",
  privileges: ["CREATE", "CONNECT", "TEMPORARY"],
});

export const databaseName = crawlerDb.name;
export const appUser = crawlerRole.name;

// Expose connection string (password is a secret output — never logged in plaintext)
export const connectionString = pulumi.interpolate`postgresql://crawler:${appPassword}@localhost:5432/crawler`;
