### Falabella.pe
POST http://localhost:3000/render
Content-Type: application/json

{
  "url": "https://www.falabella.com.pe/falabella-pe/category/cat760706/Celulares-y-Telefonos",
  "waitForSelector": ".search-results--products",
  "interceptPatterns": ["\\*.png", "\\*.jpg", "\\*.gif", "\\*.woff2"],
  "scrollToBottom": true,
  "maxScrolls": 10,
  "timeout": 30000
}

### Adondevivir.pe
POST http://localhost:3000/render
Content-Type: application/json

{
  "url": "https://www.adondevivir.com/casas-o-departamentos-o-terrenos-o-oficinas-o-locales-comerciales-en-alquiler-en-san-miguel.html",
  "waitForSelector": ".main-module__list-postings-container",
  "interceptPatterns": [
    "\\*.png",
    "\\*.jpg",
    "\\*.gif",
    "\\*.woff2"
  ],
  "scrollToBottom": true,
  "maxScrolls": 10,
  "timeout": 100000,
  "headless": false
}

### health
GET http://localhost:3000/health
